language: objective-c
osx_image: xcode10
script: xcodebuild clean test -project IPKit.xcodeproj -scheme IPKitTests -destination "platform=iOS Simulator,name=iPhone X,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
