language: objective-c
osx_image: xcode10
script: xcodebuild clean test -project IPKit.xcodeproj -scheme IPKit -destination "platform=iOS Simulator,name=iPhone X,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
after_success:
- bash <(curl -s https://codecov.io/bash)
